apiVersion: v1
kind: Service
metadata:
  name: aggregator
  labels:
   name: aggregator-service
   app: happy-paws-nagp  
spec:
 type: LoadBalancer
 ports:
  - port: 9107
    targetPort: 9107
 selector:
  name: aggregator-deployment
  app: happy-paws-nagp