apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-config-map
  labels: 
    app: happy-paws-nagp
data:
  ORDER_API_URL: "http://order-management"
  USER_API_URL: "http://user-management"
  MYSQL_URL: "jdbc:mysql://mysql-service:80/nagpassignment"
  JAEGER_URL: "jaeger-query"
  JAEGER_PORT: "80"
  JAEGER_COLLECTOR_URL: "jaeger-collector"