apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-11T16:06:41Z"
  labels:
    app: jaeger
    app.kubernetes.io/component: query
    app.kubernetes.io/name: jaeger
  name: jaeger-query
  namespace: default
  resourceVersion: "110333"
  selfLink: /api/v1/namespaces/default/services/jaeger-query
  uid: 6e4fbc0b-7c0e-11ea-8dac-42010a800073
spec:
  clusterIP: 10.20.8.197
  externalTrafficPolicy: Cluster
  ports:
  - name: query-http
    nodePort: 32214
    port: 80
    protocol: TCP
    targetPort: 16686
  selector:
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/name: jaeger
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.69.155.73
