apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-11T08:20:40Z"
  name: mysql-service
  namespace: default
  resourceVersion: "12247"
  selfLink: /api/v1/namespaces/default/services/mysql-service
  uid: 54abcc37-7bcd-11ea-8dac-42010a800073
spec:
  clusterIP: 10.20.4.69
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32666
    port: 80
    protocol: TCP
    targetPort: 3306
  selector:
    app: happy-paws-nagp
    name: mysql
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.193.201.231
