apiVersion: apps/v1
kind: Deployment
metadata:
 name: order-management-deployment
 labels:
  app: happy-paws-nagp 
spec:
 replicas: 2
 selector:
  matchLabels:
   name: order-management-deployment
   app: happy-paws-nagp
 template:
  metadata:
   name: order-management-deployment
   labels:
    name: order-management-deployment
    app: happy-paws-nagp 
  spec:
   containers:
    - name: order-management
      image: heenamittal11/order-management
      ports:
       - containerPort: 9105
      env:
        - name: JAEGER_URL
          valueFrom:
                configMapKeyRef:
                  key: JAEGER_URL
                  name: aggregator-config-map
        - name: JAEGER_PORT
          valueFrom:
                configMapKeyRef:
                  key: JAEGER_PORT
                  name: aggregator-config-map
        - name: JAEGER_COLLECTOR_URL
          valueFrom:
                configMapKeyRef:
                  key: JAEGER_COLLECTOR_URL
                  name: aggregator-config-map