apiVersion: apps/v1
kind: Deployment
metadata:
 name: user-management-deployment
 labels:
  app: happy-paws-nagp   
spec:
 replicas: 2
 selector:
  matchLabels:
   name: user-management-deployment
   app: happy-paws-nagp
 template:
  metadata:
   name: user-management-deployment
   labels:
    name: user-management-deployment
    app: happy-paws-nagp 
  spec:
   containers:
    - name: user-management
      image: heenamittal11/user-management
      ports:
       - containerPort: 9106