apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-11T16:06:41Z"
  labels:
    app: jaeger
    app.kubernetes.io/component: zipkin
    app.kubernetes.io/name: jaeger
  name: zipkin
  namespace: default
  resourceVersion: "110203"
  selfLink: /api/v1/namespaces/default/services/zipkin
  uid: 6ead7511-7c0e-11ea-8dac-42010a800073
spec:
  clusterIP: None
  ports:
  - name: jaeger-collector-zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/name: jaeger
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
